package services

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"time"
)

// THSMSClientImpl implements SMSClient interface for THSMS API
type THSMSClientImpl struct {
	APIToken   string
	BaseURL    string
	Sender     string
	HTTPClient *http.Client
}

// THSMSRequestPayload represents the request body for THSMS API
type THSMSRequestPayload struct {
	Sender  string   `json:"sender"`
	MSISDN  []string `json:"msisdn"`
	Message string   `json:"message"`
}

// THSMSResponsePayload represents the response from THSMS API
type THSMSResponsePayload struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
	Data    struct {
		MessageID string `json:"message_id"`
		Count     int    `json:"count"`
	} `json:"data"`
}

// NewTHSMSClientImpl creates a new THSMS client
func NewTHSMSClientImpl(apiToken, baseURL, sender string) *THSMSClientImpl {
	return &THSMSClientImpl{
		APIToken: apiToken,
		BaseURL:  baseURL,
		Sender:   sender,
		HTTPClient: &http.Client{
			Timeout: 10 * time.Second,
		},
	}
}

// SendOTP sends OTP via THSMS
// Note: OTP should be generated by caller, not by SMS provider
// Returns: message_id (for logging), error
func (c *THSMSClientImpl) SendOTP(phone string) (string, error) {
	// This method signature doesn't match the interface
	// We need to use a different approach
	return "", fmt.Errorf("SendOTP requires OTP parameter - use SendOTPWithCode instead")
}

// SendOTPWithCode sends OTP via THSMS with pre-generated OTP code
// Returns: message_id (for logging), error
func (c *THSMSClientImpl) SendOTPWithCode(phone, otp string) (string, error) {
	// Validate input
	if phone == "" || otp == "" {
		return "", fmt.Errorf("phone and otp cannot be empty")
	}

	// Use phone number as-is (THSMS accepts Thai format like 0631784331)
	// Don't convert to international format
	if len(phone) != 10 || phone[0] != '0' {
		return "", fmt.Errorf("invalid phone number format: %s (must be 10 digits starting with 0)", phone)
	}

	// Build SMS message
	message := fmt.Sprintf("รหัส OTP ของคุณคือ: %s (หมดอายุใน 1 นาที) ห้ามแชร์กับใคร", otp)

	// Create request
	payload := THSMSRequestPayload{
		Sender:  c.Sender,
		MSISDN:  []string{phone},
		Message: message,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %w", err)
	}

	fmt.Printf("[THSMS] Sending OTP - Phone: %s, OTP: %s\n", phone, otp)

	// Create HTTP request
	req, err := http.NewRequest("POST", c.BaseURL+"/api/send-sms", bytes.NewBuffer(body))
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.APIToken))

	// Send request
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to send request: %w", err)
	}
	defer resp.Body.Close()

	// Read response
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response: %w", err)
	}

	fmt.Printf("[THSMS] Response Status: %d, Body: %s\n", resp.StatusCode, string(respBody))

	// Parse response
	var thsmsResp map[string]interface{}
	if err := json.Unmarshal(respBody, &thsmsResp); err != nil {
		return "", fmt.Errorf("failed to parse response: %w", err)
	}

	fmt.Printf("[THSMS] Parsed response: %+v\n", thsmsResp)

	// Check status - THSMS uses "success" field
	success, ok := thsmsResp["success"].(bool)
	if !ok || !success {
		message := ""
		if msg, exists := thsmsResp["message"]; exists {
			message = fmt.Sprintf("%v", msg)
		}
		return "", fmt.Errorf("THSMS API error: success=false, message=%s", message)
	}

	// Extract message ID from data
	data, ok := thsmsResp["data"].(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("THSMS API error: invalid data format")
	}

	messageID, ok := data["message_id"].(string)
	if !ok {
		messageID = "" // message_id might not always be present
	}

	fmt.Printf("[THSMS] SMS sent successfully - MessageID: %s\n", messageID)
	return messageID, nil
}

// ValidateOTP is a placeholder - THSMS doesn't provide validation
// OTP validation is handled by backend hash comparison
func (c *THSMSClientImpl) ValidateOTP(token, otpCode string) error {
	return fmt.Errorf("ValidateOTP not implemented for THSMS - use backend hash validation")
}

// generateRandomOTPCode generates a random 6-digit OTP
func generateRandomOTPCode() string {
	otp := ""
	for i := 0; i < 6; i++ {
		num, _ := rand.Int(rand.Reader, big.NewInt(10))
		otp += fmt.Sprintf("%d", num.Int64())
	}
	return otp
}

// formatThaiPhoneNumber converts Thai phone number to international format
// Input: "0812345678" -> Output: "+66812345678"
func formatThaiPhoneNumber(phone string) string {
	// Remove non-digits
	cleaned := ""
	for _, ch := range phone {
		if ch >= '0' && ch <= '9' {
			cleaned += string(ch)
		}
	}

	// If starts with 0 and length is 10, remove it and add +66
	if len(cleaned) == 10 && cleaned[0] == '0' {
		return "+66" + cleaned[1:]
	}

	// If already has +66, return as is
	if len(cleaned) == 12 && cleaned[:2] == "66" {
		return "+" + cleaned
	}

	return ""
}
